# Generated by Django 4.2.2 on 2023-06-23 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bai',
            fields=[
                ('mabai', models.TextField(db_column='MaBai', primary_key=True, serialize=False)),
                ('tenbai', models.TextField(blank=True, db_column='TenBai', null=True)),
            ],
            options={
                'db_table': 'Bai',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Baikiemtra',
            fields=[
                ('makt', models.TextField(db_column='MaKT', primary_key=True, serialize=False)),
                ('tenkt', models.TextField(blank=True, db_column='TenKT', null=True)),
                ('monkt', models.TextField(blank=True, db_column='MonKT', null=True)),
                ('thoigian', models.DateField(blank=True, db_column='ThoiGian', null=True)),
                ('socauhoi', models.IntegerField(blank=True, db_column='SoCauHoi', null=True)),
                ('trangthai', models.BooleanField(blank=True, db_column='TrangThai', null=True)),
                ('lopkt', models.TextField(blank=True, db_column='LopKT', null=True)),
                ('ghichu', models.TextField(blank=True, db_column='GhiChu', null=True)),
                ('matkhaubkt', models.TextField(blank=True, db_column='MatKhauBKT', null=True)),
            ],
            options={
                'db_table': 'BaiKiemTra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cauhoi',
            fields=[
                ('macauhoi', models.TextField(db_column='MaCauHoi', primary_key=True, serialize=False)),
                ('noidung', models.TextField(blank=True, db_column='NoiDung', null=True)),
                ('dapana', models.TextField(blank=True, db_column='DapAnA', null=True)),
                ('dapanb', models.TextField(blank=True, db_column='DapAnB', null=True)),
                ('dapanc', models.TextField(blank=True, db_column='DapAnC', null=True)),
                ('dapand', models.TextField(blank=True, db_column='DapAnD', null=True)),
                ('dapandung', models.TextField(blank=True, db_column='DapAnDung', null=True)),
                ('mucdo', models.TextField(blank=True, db_column='MucDo', null=True)),
            ],
            options={
                'db_table': 'CauHoi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cauhoikiemtra',
            fields=[
                ('machkt', models.TextField(db_column='MaCHKT', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'CauHoiKiemTra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chitiedapancauhoi',
            fields=[
                ('malsch', models.TextField(db_column='MaLSCH', primary_key=True, serialize=False)),
                ('dapantraloi', models.TextField(blank=True, db_column='DapAnTraLoi', null=True)),
            ],
            options={
                'db_table': 'ChiTieDapAnCauHoi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChitietMonChuongBai',
            fields=[
                ('machitiet', models.TextField(db_column='MaChiTiet', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ChiTiet_Mon_Chuong_Bai',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chitietmonhoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'ChiTietMonHoc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chuong',
            fields=[
                ('machuong', models.TextField(db_column='MaChuong', primary_key=True, serialize=False)),
                ('tenchuong', models.TextField(db_column='TenChuong')),
            ],
            options={
                'db_table': 'Chuong',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hocsinh',
            fields=[
                ('mahs', models.TextField(db_column='MaHS', primary_key=True, serialize=False)),
                ('tenhs', models.TextField(blank=True, db_column='TenHS', null=True)),
                ('email', models.TextField(blank=True, db_column='Email', null=True)),
                ('sdt', models.TextField(blank=True, db_column='Sdt', null=True)),
            ],
            options={
                'db_table': 'HocSinh',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lichsukiemtra',
            fields=[
                ('mals', models.TextField(db_column='MaLS', primary_key=True, serialize=False)),
                ('diem', models.TextField(blank=True, db_column='Diem', null=True)),
                ('thoigianlambai', models.TextField(blank=True, db_column='ThoiGianLamBai', null=True)),
            ],
            options={
                'db_table': 'LichSuKiemTra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lophoc',
            fields=[
                ('malop', models.TextField(db_column='MaLop', primary_key=True, serialize=False)),
                ('tenlop', models.TextField(blank=True, db_column='TenLop', null=True)),
            ],
            options={
                'db_table': 'LopHoc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Monhoc',
            fields=[
                ('mamon', models.TextField(db_column='MaMon', primary_key=True, serialize=False)),
                ('tenmon', models.TextField(blank=True, db_column='TenMon', null=True)),
            ],
            options={
                'db_table': 'MonHoc',
                'managed': False,
            },
        ),
    ]
